// import './globals.css'
// import Navbar from '../components/navbar'
// import type { Metadata } from 'next'

// export const metadata: Metadata = {
//   title: 'HR Dashboard',
//   description: 'Employee Management System',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className="bg-gray-100 min-h-screen">
//         <Navbar />
//         <div className="max-w-7xl mx-auto">{children}</div>
//       </body>
//     </html>
//   )
// }









import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
